---
services:
  devcontainer:
    build: .devcontainer
    init: true
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker-host.sock
      - .:${LOCAL_WORKSPACE_FOLDER}:cached
  hass:
    image: "homeassistant/home-assistant:${HA_VERSION:-latest}"
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - .devcontainer/preconfig.sh:/etc/cont-init.d/preconfig.sh:ro
      - .devcontainer/preconfig:/preconfig.d/01-integration:ro
      - .devcontainer/config/configuration.yaml:/config/configuration.yaml:ro
      - .devcontainer/config/specific_configuration.yaml:/config/specific_configuration.yaml:ro
      - .devcontainer/config/www:/config/www
      - ./custom_components:/config/custom_components:ro
  frigate:
    privileged: true
    image: "ghcr.io/blakeblackshear/frigate:${FRIGATE_VERSION:-stable}"
    restart: unless-stopped
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri:/dev/dri
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - .devcontainer/frigate.yml:/config/config.yml:ro
      - ./frigate:/media/frigate
  mqtt:
    image: eclipse-mosquitto:1.6
    restart: unless-stopped
